#! /usr/bin/env python

import re
text = open("oldmpiconstants.m4").read()

regexp = re.compile("AH_TEMPLATE.*?DUMPI_HAVE_([_A-Z\d]+)")
matches = regexp.findall(text)

str_arr = ["AC_DEFUN([DUMPI_CONSTANTS], ["]
for m in matches:
    line = "AH_TEMPLATE([DUMPI_HAVE_%s], [defined if %s is available])" % (m, m)
    str_arr.append(line)
    line = "AC_DEFINE(DUMPI_HAVE_%s, [1])" % m
    str_arr.append(line)
str_arr.append("])")

open("mpiconstants.m4","w").write("\n".join(str_arr))


